# Generated by Django 4.0.2 on 2022-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=80, verbose_name='Названия')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('surname', models.CharField(max_length=80, verbose_name='Surname')),
                ('news', models.TextField(verbose_name='Описания')),
                ('is_published', models.BooleanField(default=True)),
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
