# Generated by Django 4.0.2 on 2022-04-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='user',
        ),
    ]
