# Generated by Django 4.0.2 on 2022-04-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_rename_content_women_cont_alter_women_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='media',
        ),
    ]
